"""Canonical, vendor-neutral domain contracts (Pydantic v2).

Every downstream module consumes these types only. Sensor-native fields may be
carried inside ``metadata`` but never become business identifiers.
"""

from radiowave.contracts.confidence import ConfidenceDecision, ConfidenceThresholds, Decision
from radiowave.contracts.events import (
    CartEvent,
    CartEventType,
    RetailEvent,
    RetailEventType,
    make_event_id,
)
from radiowave.contracts.geometry import (
    STORE_FRAME_ID,
    SensorCoordinate,
    SpatialUncertainty,
    Vector3D,
    Velocity,
    WorldCoordinate,
)
from radiowave.contracts.observations import (
    NATIVE_ANTENNA_KEY,
    NATIVE_POSITION_KEY,
    NATIVE_TRACK_KEY,
    AnyObservation,
    ItemObservation,
    PersonObservation,
    SensorHealth,
    SensorHealthStatus,
    SensorObservation,
    VisionEvidence,
    VisionEvidenceKind,
)
from radiowave.contracts.sessions import SessionState, ShopperSession
from radiowave.contracts.store import (
    EPC,
    Boundary,
    BoundaryKind,
    Box2D,
    CoordinateFrame,
    Fixture,
    Item,
    Product,
    Sensor,
    SensorPose,
    SourceType,
    Store,
    Zone,
    ZoneKind,
)
from radiowave.contracts.tracks import (
    AssociationEvidence,
    CandidateScore,
    InteractionCandidate,
    ItemState,
    ItemTrack,
    PersonTrack,
    PersonTrackState,
    TrackPoint,
)

__all__ = [
    "EPC",
    "NATIVE_ANTENNA_KEY",
    "NATIVE_POSITION_KEY",
    "NATIVE_TRACK_KEY",
    "STORE_FRAME_ID",
    "AnyObservation",
    "AssociationEvidence",
    "Boundary",
    "BoundaryKind",
    "Box2D",
    "CandidateScore",
    "CartEvent",
    "CartEventType",
    "ConfidenceDecision",
    "ConfidenceThresholds",
    "CoordinateFrame",
    "Decision",
    "Fixture",
    "InteractionCandidate",
    "Item",
    "ItemObservation",
    "ItemState",
    "ItemTrack",
    "PersonObservation",
    "PersonTrack",
    "PersonTrackState",
    "Product",
    "RetailEvent",
    "RetailEventType",
    "Sensor",
    "SensorCoordinate",
    "SensorHealth",
    "SensorHealthStatus",
    "SensorObservation",
    "SensorPose",
    "SessionState",
    "ShopperSession",
    "SourceType",
    "SpatialUncertainty",
    "Store",
    "TrackPoint",
    "Vector3D",
    "Velocity",
    "VisionEvidence",
    "VisionEvidenceKind",
    "WorldCoordinate",
    "Zone",
    "ZoneKind",
    "make_event_id",
]
